In [1]:
from google.colab import userdata
NVIDIA_API_KEY = userdata.get('NVIDIA_API_KEY')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
! uv pip install langchain langchain_nvidia_ai_endpoints langchain-community pypdf "unstructured[all-docs]" faiss-gpu-cu12 "nemo-microservices[data-designer]" deepeval

Using Python 3.12.12 environment at: /usr
Audited 8 packages in 691ms

In [4]:
from langchain_nvidia_ai_endpoints import ChatNVIDIA
LLM_MODEL = "nvidia/nvidia-nemotron-nano-9b-v2"
llm = ChatNVIDIA(model=LLM_MODEL, temperature=0.6, top_p=0.95, max_tokens=8192, api_key=NVIDIA_API_KEY)

/tmp/ipython-input-1458240435.py:3: DeprecationWarning: The 'max_tokens' parameter is deprecated and will be removed in a future version. Please use 'max_completion_tokens' instead.
  llm = ChatNVIDIA(model=LLM_MODEL, temperature=0.6, top_p=0.95, max_tokens=8192, api_key=NVIDIA_API_KEY)

In [5]:
llm.invoke("Hi")

AIMessage(content='Hello! How can I assist you today? 😊', additional_kwargs={'reasoning_content': 'Okay, the user just said "Hi". That\'s a greeting. I should respond politely. Let me make sure to acknowledge their greeting and offer help. Maybe say something like "Hello! How can I assist you today?" That\'s friendly and opens the door for them to ask questions. I should keep it simple and welcoming.'}, response_metadata={'role': 'assistant', 'reasoning_content': 'Okay, the user just said "Hi". That\'s a greeting. I should respond politely. Let me make sure to acknowledge their greeting and offer help. Maybe say something like "Hello! How can I assist you today?" That\'s friendly and opens the door for them to ask questions. I should keep it simple and welcoming.', 'content': 'Hello! How can I assist you today? 😊', 'tool_calls': [], 'token_usage': {'prompt_tokens': 14, 'total_tokens': 98, 'completion_tokens': 84, 'prompt_tokens_details': None}, 'finish_reason': 'stop', 'model_name': 'nvidia/nvidia-nemotron-nano-9b-v2'}, id='lc_run--019bb02f-2df3-7483-9c20-07de8eca1b53-0', usage_metadata={'input_tokens': 14, 'output_tokens': 84, 'total_tokens': 98}, role='assistant')

In [6]:
!apt-get update
!apt-get install -y poppler-utils tesseract-ocr

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:4 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (2,716 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
poppler-utils is already the newest version (22.02.0-2ubuntu0.12).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.

In [7]:

# UNCOMMENT IF NO EMBEDDINGS IN THE DRIVE

# from langchain_community.document_loaders import UnstructuredPDFLoader

# # Recommended values for the 8,192 token limit of NVIDIA NeMo Retriever
# # Assuming ~4 characters per token, 16,000 chars is roughly 4,000 tokens.
# MAX_CHARS = 16000
# SOFT_MAX = 12000

# loader = UnstructuredPDFLoader(
#     "/content/qps-ugs.pdf",
#     mode="elements",                # Essential for identifying Titles, Tables, and Images
#     strategy="auto",                # Fast for text pages, hi_res only when needed
#     chunking_strategy="by_title",   # Keeps section context together
#     max_characters=MAX_CHARS,       # Hard limit to stay under token window
#     new_after_n_chars=SOFT_MAX,     # Preferred chunk size
#     combine_text_under_n_chars=2000, # Merges tiny fragments into larger chunks
#     overlap=0,  # Not needed for clean semantic chunks
#     pdf_infer_table_structure=True,  # Optional: adds HTML version of tables to metadata
#     # show_progress=True,
# )

In [8]:
# UNCOMMENT IF NO EMBEDDINGS IN THE DRIVE

# Load the structured documents
# docs = loader.load()

# print(f"Total chunks created: {len(docs)}")

In [9]:
# UNCOMMENT IF NO EMBEDDINGS IN THE DRIVE


# # Inspect chunks
# import pandas as pd
# from unstructured.staging.base import elements_to_dicts

# # 1. Convert the list of elements/docs into a list of dictionaries
# # If you are using LangChain's 'docs', you can access the original elements if needed
# # or manually create a list of dicts from the Document objects.
# element_dicts = [
#     {
#         "page_content": doc.page_content,
#         "category": doc.metadata.get("category"),
#         "page_number": doc.metadata.get("page_number"),
#         "filename": doc.metadata.get("filename")
#     }
#     for doc in docs
# ]

# # 2. Create the Pandas DataFrame
# df = pd.DataFrame(element_dicts)

# # 3. View the first few rows
# df.head()

In [10]:
from langchain_nvidia_ai_endpoints import NVIDIAEmbeddings

client = NVIDIAEmbeddings(
  model="nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1",
  api_key=NVIDIA_API_KEY,
  truncate="NONE",
  )

In [11]:
# UNCOMMENT IF NO EMBEDDINGS IN THE DRIVE


# from langchain_community.vectorstores import FAISS

# # This will automatically call client.embed_documents() in optimized batches
# vector_store = FAISS.from_documents(docs, client)

In [12]:
# UNCOMMENT IF NO EMBEDDINGS IN THE DRIVE


# # Save to your Google Drive persistently
# vector_store.save_local("/content/drive/My Drive/my_project/faiss_index_fpga_copilot")
# print("Vector store created and saved to Drive.")

In [13]:
!uv pip install rich

Using Python 3.12.12 environment at: /usr
Audited 1 package in 87ms

In [14]:
from rich import print as rprint

In [15]:
# Loading embeddings from the drive

embeddings_path = "/content/drive/My Drive/my_project/faiss_index_fpga_copilot"

In [16]:
import os
from langchain_community.vectorstores import FAISS

if os.path.exists(embeddings_path):
    # Load the vector store
    # You MUST provide the original embedding client (NVIDIAEmbeddings)
    vector_store = FAISS.load_local(
        embeddings_path,
        client,
        allow_dangerous_deserialization=True
    )
    print("Vector store loaded successfully from Drive.")
else:
    print(f"Error: No index found at {embeddings_path}. Did you save it first?")

Vector store loaded successfully from Drive.

In [17]:
# 1. Define your test question
query = "What is the primary function of the Intel Quartus Prime software?"

# 2. Perform the search
# k=3 tells it to find the top 3 matches
results = vector_store.similarity_search(query, k=3)

# 3. Print the results with metadata
for i, res in enumerate(results):
    rprint(f"--- Result {i+1} ---")
    rprint(f"Page: {res.metadata.get('page_number')}")
    rprint(f"Type: {res.metadata.get('category')}")
    rprint(f"Content: {res.page_content[:300]}...\n")

--- Result 1 ---

Page: 6

Type: CompositeElement

Content: Intel Arria® 10, Arria V, and Arria II

Intel Cyclone® 10 LP, Cyclone IV, and Cyclone V

MAX® series

The Intel Quartus Prime software GUI supports easy design entry, fast design processing, straightforward device
programming, and integration with other industry- standard EDA tools. The user interfa...

--- Result 2 ---

Page: 9

Type: CompositeElement

Content: Note:

Intel replaces the following Altera tool names in the Intel Quartus Prime software:

Table 1.

Intel Quartus Prime Tool Name Updates

Altera Name

Intel Name

Qsys

Platform Designer

TimeQuest

Timing Analyzer

EyeQ

Eye Viewer

JNEye

Advanced Link Analyzer

Related Information

Migrating t...

--- Result 3 ---

Page: 1293

Type: CompositeElement

Content: Intel Quartus Prime Standard Edition User Guide: Third-party Synthesis

3

683796 | 2018.09.24

Send Feedback

1. Synopsys Synplify* Support

1.1. About Synplify Support

the Intel® Quartus® Prime software supports use of the Synopsys Synplify software design flows, methodologies, and
techniques for...

In [18]:
# SETUP RETRIEVER TOOL FOR CHAT
from langchain.tools import tool

@tool(response_format="content_and_artifact")
def retrieve_context(query: str):
    """Retrieve information to help answer a query."""
    retrieved_docs = vector_store.similarity_search(query, k=2)
    serialized = "\n\n".join(
        (f"Source: {doc.metadata}\nContent: {doc.page_content}")
        for doc in retrieved_docs
    )
    return serialized, retrieved_docs

In [19]:
# CREATE AGENT and append tool
from langchain.agents import create_agent

tools = [retrieve_context]
# If desired, specify custom instructions
prompt = (
    "You have access to a tool that retrieves context from a FPGA Docs. "
    "Use the tool to help answer user queries."
)
agent = create_agent(llm, tools, system_prompt=prompt)

In [20]:
for event in agent.stream({"messages": [("user", query)]}, stream_mode="values"):
    final_message = event["messages"][-1]

print(final_message.content)

The primary function of the Intel Quartus Prime software is to serve as a comprehensive design platform for developing and optimizing FPGA-based systems. It supports the entire design flow, including project setup, synthesis of VHDL/Verilog/SystemVerilog code, design optimization, debugging, and integration with third-party tools. Its modular Compiler and user-friendly interface streamline FPGA development, enabling efficient creation of high-performance hardware designs.

In [21]:
query = (
    "What is the primary function of the Intel Quartus Prime software?"
)

for msg, metadata in agent.stream(
    {"messages": [{"role": "user", "content": query}]},
    stream_mode="messages",
):
    if msg.content:
        print(msg.content, end="", flush=True)

Source: {'source': '/content/qps-ugs.pdf', 'file_directory': '/content', 'filename': 'qps-ugs.pdf', 'last_modified': '2026-01-07T21:27:21', 'page_number': 6, 'orig_elements': 'eJzVW1tz3Day/isovWxyShgTBEACfnM5To6rsmvtyvGeqmzKBQLgDGMOOeZF8ji7/327AXI0o0ssHUfa2QdVqUkQaPTlQ3ej5+ffTnzt174Z3lfu5Dk5YcpkvMxLqrWQVJiU0UKVJS0LJU0muLSFPTklJ2s/GGcGA9/8dmLbtnNVYwbfB7o223Yc3q98tVwN8CTX6SKBj6bnl5UbVvA4Y/Hxpq2aAb/8+WcmJT5Keb7IfzklO1rkC400Z2rBb6HDeHhw0m/7wa9xJ2fVJ1+fb4z1J/+CF2VV+/eu6rwd2m6LA57Zthlg5yfT28asPT7/uOnpuOwXG1eeBKb74f26dVVZ+SCiNEkzmjCa5G9T9jzNn6cMx23M0r9vxnXhO9wbrjn4T7j9k9ewTk1edF1l/jEmifGEwaYCTd6dEtO4iXj9GmcatpvAyNtqqAPz15WUS2+dcsCCSBQVaaGpSoSnptTKpaIsQEuPqSSQNipFiklJE53xiRZsoW+hw/ijVdK+5H+s+uE1sniL8FOZ26IsBDVMeyp4wmkh8pyW3HtTcGWVVE/gIZIv5L6HzMLmOby4hQ7jj1b40UNebm3dNn7nI+THs9P5IXk9ecpMv7uXq7C0VNKzkirODLiKATwD7VGrM13w3Mi0zJ/AVTK94PuukuuovZSxRXoLHcYfrbb+/OL/Jh31vqtASPd0HeW0FaJQVJYupSLngFvGZhT+tLZS24w96uEyCV8nB8rgIo3Cl5yhq1yn4/ijVcbbFfhGcJ+/jqYbxp6cddUaVNOWw6XpPPnhp9ekHzebtht64k2/Jc731bIhwF63PSUl8DA/2nSt9X1fNctT0g+dQRmXbQfzOBhyUVmPQ5adWa/DGHRIkK+HJ0PVNuSyGlakHVa+g8duhCm2FCaCYTjDq+9ekKFt635BkOuxD8MG35UgSLI2H3xPqiHyCKsSUCiMh38t7ApmB7qbOP3HmCZMkKYd8AUsOO8A54/Tg1jH2nTkZbvegAY63JA367pqYBn84vuzH17grnzdbtBK593HbfmmH7tp5Ark4EFKG2C17damAXaRQXxXe5SfL4EeFvue8BfToVQu/FvU1C3u4J3QJpMllcI5cAetaeEFAJRL4BhXqUkce0R3yMMTDqdy8IaJhHMjOgfLFuoWOgw/Wmf4vlqC0ghb3OtwgENSOaEcRE8egl3NPNW5LSlL8iwDGCiNyB4fj3YamOlZ5FxnAY+u08etgtuw6HyHAK4KOHG+B073U1XpE/ANB0eHgKPDGUWLhBdUMJkLpoQW+jGjLiUX+SnJ9BR0RTKX06kuVHobHYcfuaJeth2cDAG9F+RFXZMOhdMTgD7fXXi3iIfLacC6+EndLtuIkRHp49O16T70BHUK54bzkWxLcmMZAsBZwQr9WPSVqwxGENMq5BIxE4R+gLQwCY4PcI2r9n5dgZTciEJD0Mb/ejwp7Nh1COT9xluQjA3rwZnSEGMt2EKYLpxRYbk/9Vdn07QynIfFOMy7j+gfJILT4wlF7Mo0Sx+WM832avnIWYdnJBBDeDmg8eN6YF54VsG7eaem78c1jGxaXGwDbFZFVVfDFsVTV2YiQDp4GhOcAOSA7JjNpp62hmPhFMU3uFzVBJnhm9OZsVMcM/GFZ6TtqsI7AnrzIBb/yfoN8AqBwacN8NHXsOSy8zAC9gcDLjtwWFi/2Ea+Z/bhRB7ate+ixo27qPr4TVsMpoonco2ON5ALGBV4LecQ4pp6Cg9sg5h9vQ1bbaJgx6Ku+pV3+9sKUp7Gb2pjw/jOIR/lvi1c7RlM63/eBDNFT4pqKkDTrgd1bmEuYmsDanIoBOQa5gDjQz2U0b77h53q3OYmkaWnmUg1FUInVAsuqMwcF0VSaGYe81SHUwwf5UkeoWqmIZblMajlAauu02H8fxarIDL7EDbx2wm4ZQcCbZz/BA+SfdQ6f4Njx65GajUMm/75s2eXl5eLKtinbdczW/j02dg/882zj6NBd3oWxtCqb2nnlxVGuMEEF6thXUdlHq4s9lbWScLIcwJxp3xCDtg+C38Ln4Drukfj4JcvHBrnbwgK4jmKgRzy8+VkXGmXeK6oMZ7D0V0wqlSRUc8KqXmZFZlJH9E1eMKxWCjZVBmZSB1JycMH10l2ZDWrfF8bLMBxBD1ER8DfAM9Tdj4FYRN1eyh239zd5TIxWZ5Sb7CQoi3Amhc5zZg3eVlKk7rH1J0QKoRUcsECqkUScha2p6xrZBh8tLrLFBe5JP9EQNEL2DHL9nXxUwPHo1+2XfXZuzszSJkJlSWSMmkgg4Q4mBp0qIJLr3VmjMkfUylTwqJVLMZPJEunYpZkAvOV63QYfrRquaucciOF2dVX2rIMcRApRwyfMTrE2KH0ZggFBIMVDbsim5WJodpetaKs20v02n7VdrC//QoHsVtb+xCvwNeVv/B3lSKePyg+cSzTaZkZypwRVCiwHlWWKTWlLHlmlGapf3ybYTw7SHqZkBMdLwtu0GH80VrNvS8PCpV6nTHKXQ4noE051QlktTbJZeptro17guu1K+FPtFKTh6Kr3kIfgfDvDA45k/uladOYJWYFwYf3oqSxqT6O/n16W4zF+X6Eeej3Z137K2yqv3Wqm8HSgVW8wkLmNAE598O4iWXLj2NlP0CmZTvACHBx0vhLzDtwHCTWzu3gAeQ2lSNjzrQNGADML/0wwdSUU4WsFl/+Beaa1/x79Rkga0FexoVAyABVmCB38FEfki/AowA60/Ihi27XGxMSsn6sIZkKU1992/sBU0JIrM7NBEq7vHvAZa5PiezP/4cdYaplCOa1tT8Ny2HqCSkYvl1AVAkrISOHyiS3KwbzRdQB0SEFXGNquJcxPix5KxVLc2sYtQCMWJItqC41oym3shTOuDwpnwActTy8LkplPGEl/JPepOP4owXH76Ixn9WmaVCbb/EKYCrgQxLfBL1VDRyrpiavn70hm6ohUVinZNNegjEAr/243sTKRjgSwaLJOFQ1WHg4jqeawyvTgWOdhY9e9UMFRtB2sXgVH75oTL39DP8gF3Gu8LKaGPTdngFe53w2NS6/bGu/dwwkKkly5RzNtMJgWhQUzl1GDbOJk85mXMgnuAiDMPngAl+Jyax4grX+G3QYf+xm9hJMBW+uAI5e4QVXNLQdfFbx4gqLR0Ej+4VMu/u0v8LT8wnuAAFN3S5J0X46JS96XCtcGmE8iCa2Z0FxzrdhqZ3BLci7qscU/HMM6sJmt1hMrewVO2FdrFeSiwqAfBctBoyHaLHtgsdM1v5yVW3mRffXfFm3eHlFvp8/2LPpewW3P+HV3A9j5fxzckOu/dcZv80yU3gvqdHK45W8BoyVGeU2S60TNmOP20Ax3wKzA+PnSXLQrXKdjuOP1vjvK/xCG8NVJijLlKLCa0tNkRiacydS56TP06fo79oJP9Kc8zlzTxbsJn0Mwr8zAGU5e+j115V7kee7++k7SnqmHnxnQk3PtXZEXQZ/e7YZegYBuhBZwjUX/M4C3oGhvJ5u6yHaOt82ACJ9NZ3FEKJdAEc93mVXtgrx3DxibiAInv/uf7/7kXzDtMox9NDYf5ck6ttT8s53FULk9F7L8IZ9G/HwPKhuHvMNvJHfHrQiwJnfLEdgvf8auNpd9399NOiEKE1iS2q1slQ4LqnWWUI9LyEg5DwrmH6C+2GuD+orXMz1lgmprtNh/H89UuXArEq5odokJRXSOlp4LakyUshEFbkW5vGR6kr4E63me5NYzLpBH4Hw70SqNBG/j1R/EATdzLDTdH/l48JDyMLDJPW0cphthsR4Dxyvgad0OKSz1xqBxiZeC7spnqsOS3mQ72Iv08H9sa97f4nXsNiBZfG214Sb1qHdUNdehrvdoh2Gdk3HDRm8WdPCYJI8zQl2v2pdi+sdDWAqb5USpaDSuZwKCxmOsTqlJpOG+0RnOk2eADCVitHDRAuRzHedySK7ScfxRwuYbzaYtHxG2/hbNMFonFNcHpgkrz5talAdZAEjWAwoyZq6xk4/cJb1ruOtwMoxeE6B4p7u5OdyztxxNxvtYg78MdfBNomBXED24lBP1+o7S8gKsCTd+d16OzPtRiz44NzLEHTYurUf+tPQYQEBBgwxNZa4INSwq65tWjDaXTOisdgyMVfAwljS4Xax/aOK15Zfn9lMAo4S+bq8XhoPybunLFUpFcprWmitqE99ofLSZCkXj2//QuQH9i/TZM7jxULcpOP4o7X/SUvf+WJcYjUwWj/e05xHi3hrNhPsmrm4Y81munwBw3FVDznwFnuaTE1DT85kS4VfmYsqVJ9g5NwQii/B5Oq6vYyATPwng0Y9+dD0DbYlYfMqTjTZMXFjh580aDm70iz2k1y1x2InD87TYJMNWhtsszNz3Su0rsCTOG1tCuI/jlVoT41drW870/TWAwjHEtaHKvStxsj9aoOonQ4LXOu2wfrErlvXzWKcawvD3oQhcgCX3VW7gp8XbSgif42fwZqx7PeV/pUbmYvcUa18jg0EcL54ndA884W0mct58gTd/DLND0oHkmcHpYIbdHpsv076fwXkABt5rjEb8hLATTpDVakymgldMJlLxvJHzYZiAH4l/InO9VwLTwO4XaePQPh3B+Spuh6QPzTq/bW7jFGvyHIBKfndITjfD8EfUqA4g5AYfXU6Lx8emd+bR5bnh/K42doSQfr1GXaU+ltu5cQXI/5YhwhgCNPM9ZBdzO98iVCPr5e+QeTGGzq8pKohuCHRivDAWI92RSC46WOb5wBxPRlDsyY2wAY5GgRg04wA5fu/koih+1RjviFd8s2sjm8PQfdLwthdT0gWd/dQnL7Jyh9QQ5HG2QySd6YBqEH7ghZZmtDEKudEYtyT/OZHquwQsrU8hOjrdBj/Xw/ZWZHrrOCcGl4qgOyypEWiCprlWpaK2TzjT1BDuRJ+pDOWzzUTdRt9DMK/u9or+Z4i3q4q8CX6UEBcDgMCopaZSrkW6d2AmO13JpwZ7Es+r9ZjLFI83rKK3dwkmZafa8IPXv3XZVg9ExLiCJXerz4TFqebsDT+fgyjSHIeq9ERsGdknXogpko1BNdT43kfI93DaXaV7VOI3Wd5xgg5hLu0xt+FTdeFMa/AMvj067UdKkfuyHXFxLu48O6a0OKP3pZjCNf/AHRVKhElCw0KGRU851TnRkPqmQkljSyL4gkq1Fl6WHDJ1K7AwjAGu0Gn//mCy90xmc72gwWQtx2iDdx+oM5tgHv9tIcRibyHjd/ec3jWtTfbDf2nTfj1QvzZY+8x142/Fql8Pyd19zn6T+fGnJg7Rm6v2hYhnhl21z57P+e4CjywAyiI584lr5iedhEm3S25d7U9L4Qs7VjAmmmH+S8WSU1PHqyMXUSU73768ru/5vjl3z60Hdo=', 'languages': ['eng'], 'filetype': 'application/pdf', 'category': 'CompositeElement', 'element_id': '464ed7d23ca3b77236faad53d094f3b0'}
Content: Intel Arria® 10, Arria V, and Arria II

Intel Cyclone® 10 LP, Cyclone IV, and Cyclone V

MAX® series

The Intel Quartus Prime software GUI supports easy design entry, fast design processing, straightforward device programming, and integration with other industry- standard EDA tools. The user interface makes it easy for you to focus on your design— not on the design tool. The modular Compiler streamlines the FPGA development process, and ensures the highest performance for the least effort.

Figure 1.

Intel Quartus Prime Standard Edition Software GUI

Intel Corporation. All rights reserved. Intel, the Intel logo, and other Intel marks are trademarks of Intel Corporation or its subsidiaries. Intel warrants performance of its FPGA and semiconductor products to current specifications in accordance with Intel's standard warranty, but reserves the right to make changes to any products and services at any time without notice. Intel assumes no responsibility or liability arising out of the application or use of any information, product, or service described herein except as expressly agreed to in writing by Intel. Intel customers are advised to obtain the latest version of device specifications before relying on any published information and before placing orders for products or services. *Other names and brands may be claimed as the property of others.

ISO 9001:2015 Registered

1. Introduction to Intel® Quartus® Prime Standard Edition

683475 | 2019.12.16

The Intel Quartus Prime Standard Edition software offers a full range of features at each phase of the design flow to shorten your design cycle and achieve the highest performance:

Easy Project Setup—quickly create a new project, add design files, and specify the target Intel device with the New Project Wizard. Create different revisions of your project to compare results with different settings. Save the current state of your project and project files as a single, compressed file. Refer to Managing Intel Quartus Prime Projects on page 9 for more information.

Design Planning Tools— plan for initial I/O pin layout, power consumption, and area utilization in the Early Power Estimator, the Power Analyzer Tool, and the Pin Planner. Refer to Design Planning on page 35 for more information.

Design Constraint Entry—specify timing, placement, and other constraints with the Settings dialog box, Assignment Editor, Pin Planner, and Timing Analyzer. Visualize and modify logic placement within a view of the device floorplan in the Chip Planner and Timing Closure Floorplan. Refer to Intel Quartus Prime Standard Edition User Guide: Design Constraints for more information.

Integrated Synthesis—provides efficient synthesis support for VHDL (1987, 1993, 2008), Verilog HDL (1995, 2001), and SystemVerilog (2005) design entry languages. Refer to Intel Quartus Prime Standard Edition User Guide: Compiler for more information.

Incremental Compilation—preserve the results and performance for unchanged logic in your design as you make changes elsewhere, facilitating top-down or bottom-up team-based design methodologies. Refer to Intel Quartus Prime Standard Edition User Guide: Compiler for more information.

Optimizing Results—Design Space Explorer automatically determines the best combination of settings for your design. Design Assistant validates your project against predetermined design rules for gated clocks, reset signals, asynchronous design practices, and signal race conditions. Refer to Intel Quartus Prime Standard Edition User Guide: Design Optimization for more information.

Design Debugging—The Signal Tap logic analyzer captures and displays real-time signal behavior in an FPGA design, allowing to examine the behavior of internal signals during normal device operation without the need for extra I/O pins or external lab equipment. The Transceiver Toolkit provides real-time control, monitoring, and debugging of the transceiver links running on your board. Refer to Intel Quartus Prime Standard Edition User Guide: Debug Tools for more information.

System and IP Integration—define and generate a complete system in much less time than using traditional, manual integration methods with Platform Designer (Standard). Refer to Introduction to Intel FPGA IP Cores on page 51 and Intel Quartus Prime Standard Edition User Guide: Platform Designer for more information.

Third-party EDA Tool Support—integrate with supported versions of third-party EDA synthesis, simulation, and board-level timing analysis tools. Refer to Third- Party Simulation and Third-Party Synthesis user guides for more information.

The Intel Quartus Prime Pro Edition software expands on these capabilities of the Intel Quartus Prime Standard Edition, and provides unique features that support the latest Intel FPGAs. Select the Intel Quartus Prime software edition that provides the device support and features you require, as Selecting an Intel Quartus Prime Software Edition on page 7 describes.

Source: {'source': '/content/qps-ugs.pdf', 'file_directory': '/content', 'filename': 'qps-ugs.pdf', 'last_modified': '2026-01-07T21:27:21', 'page_number': 9, 'orig_elements': 'eJzNW21v3MYR/iuEvhQotNd9f/GHAkZapy4S10mc9EMQGPsylFifjheSZ1lJ8987uyTlk+7snFucS8CQ9VBL7u48nJlndpc//noBa7iBzfC6SRdPqovgpNRcWsJ0qol0dSKWQyTaJp20UioJenFZXdzA4JMfPN7z60Vs2y41Gz9AX/Da37W74fU1NFfXA14xjq8o3jRdv23ScI2XNRsvb9tmM+Q7f/zRlCvOrtxPl9WEGDUjZJSu5CEurRFf9Hf9ADd5Fi+bd7D+busjXPyGf6ibNbxOTQdxaLu73OBPsd0MOOuL6a8bfwP5+s/bnuyu+tU21RdlwP3w+qZNTd1AMQ+nXBPKCDWvOHvCzRPOcrutv4LXm91NgA5budznAO/y1C9etAM8yW2Gu23p4lUzrMuwHpveWMtdsp6ASIJI6RLxUTjCjfQ+OCeTdGc0PRNm3/YTvDe2om5lD/Gyjf8c+1lXHWzXOJq+Gq6hqtv1ur1tNlfV0/UAna+Gtl1XeQh91WxKk/Gub3a+G3Z99bJrbqDq23q49d1DKl/4rvND8xZe5f6OUErBxcSSIwL7R2/ygoRIOfHMB9BcM03t+SllzK3MPqfcTtiYFT+CS/vFkvrKhzVUbHWSU1keEvNKEPSuSCRgKAtWamKkTAx0Levgz8gAzu4BAzOeLS6pWLkjeNkMHHOQV9mNXmCX1ffbVCx3Ej2Ya+rkNVHGOyKDDcQK5UgMIUFdJ2YpnJUes2JobmFXaqRnxFJNWKlCx2Nc2i+WnimwZTJOSzypdgHjEmE0KiJrRYmNLhCIEpSuWQpWnZEE4dxK7ZEw49noUoqVPoKXTcLoIydzoKgx2hlDaMRupJKZgxoIcC2FZanmkZ0zUyhdIr+SK1kywYQ1m7ARR3Fpv1gOvsFRnSi9gqA1pyR4Z4jU6AsBLU/AKqk8Nc7ac0ovwcxK7Fl/xrO1hR2F72O8bOu/XPuhbrub6i/QN1cbbHAKFRhrkjWiJlFLDEaBCeI8pgWn6wjeRAP+nMFofvENXYl9R0BlNGInSwI/wLn9Yql4hRn6mx30w0kUyIC2NrEm1GXNpKUnNjhOdEgpSA2M+fozeMNMwT2eTC4w9thjeOkUlKJj49d3v5zoCzZKSZ1xxFuJFSHOGNWRxgClPOPUK4bR6jP4gsX/9n3BiQkbWcLQY1zaL5aIv97BN6e5AZpYu8CIUhZTcp0scVZTEmUtaNQ1VhbpM7jBbP0Zz9YWj9gQ+2wt2frVDw3cnugBjnkhXeAEUkhEIiXEJayilUNdFFJd68TP7wG5amN7HsCpmzDGIHkM5/aL5eDvL5CFk8yfrI86KUNi4p7IpCUJAnMCYOXsPKAssp/BBe7Nf48nc0tKc+Q/xIs2/9P01m8ipOqrZvPmExOCqA1WY4JwBxrTgLPEaqOIp5aKIKTxVp9/PYlz+WA9iQsxrW4IlyuzA1zaL5aPbwGFKtLxfJPVqh+adnMSGZpSivWxJUlKR6TFas3KUBMlapkUldTW4jOQIelYFt9jN5XRtpTRh5j+38vmNb74ZRK/XvSD79CgmwTv8ALdo+Xr5iovrqJmGtqjS7Ivu7b6a2pmvnbdOt+22zQ/7+C1ufjtp4/T/inPr/BfflRl5EmvhpCeK86xfnGom6WRlgR8JQgLMloua5DpnOu+474J13ql32+jcBQKtKzcc3YUl+aL9VK24qtMU9emXSycfIC27wa/Sb5L99x9C2+bPv/yt6Yv4z6FQY66ozYQSS0jzzUQMugx81kvNPDAOGPn3AdzLq8zCmpHbTdBpmahzfMy5QEuzRfL4F/auMsWrn6Arj81yGL1E730iTCIEgUg08SCisTVQXuqtLPsrOtijuWgeU/EjLkYXYvrsgt2gJfNxDG3+RRSaMIY5qIgyWFQk0orrIwsJYEb58DHoNlZF4yxxJF7pMx4dgfJRhIe42WT8sW131yduG0igOsUDQoOISyWpnVNvHWSKGasR1moXDjntgljOus6IfgkPWY8SQ2mShl0iPn/XXp8hABO8T3ByTK9z8H3m4gWu2q75hdIH9rnlZZFz50jHCzq8sgD5nsNxNSuRs9IKvlzLtRwTnNZes/HPZ7sz6Uo+eEAL5oPZEOu6CdzQYPhHJglvqaJSCrRS1xNMXNz7513JsE5ZTm3tGSIey4mLO/PTbDCzWO8bC6epoQV0rZrUTPflIXM3F91BRvoSsVU9bvttu2GCmuoSZY9vcIm76qE8itC/2C7/itUYs/zLI8pr9orqhwlwBX6EjBHvIkpF7rBRc2xxj13bDPIh9IrO8e2jLWY8BTLHuPSfrH8YWyzK+pWXH6yP9VGa5VqRWLNBBY0wRBPTSQovai0gkLNz7k3NseymY8Zz/afY9ljvGw+kA32X8Q2LEms1VhXUpZSXnJAIZykIbWlTnJj4MynWaZYds/FhGfbS6OK0HqMl83F8w3WiT4fE1uD72Evgn28sDztAJLxPiZJBcGaEbWy1Og+0uH4YuIalbJX9pzpaKz9DWaXvROVBoVAgYKKTOAh5ss/1fc7Vf/3PXTVl7smwZPqSxjKQs93ebEJ0mlL38oZy5EoAIuFp6Kc2KDwRx1qgGhkkOfcBJVGjExNuz8zltNujxL8KBaL3v35DjapegaQgo9v9ml41rYDNj9W6sRaS+o4AZ93gFjCMlMDxj3Fk5DRO/45/Efxca95hm6CurjLY8iXvBFtT7O70tHG6BIJwNDuATO+BW6JsaAgChmSOmeNj5kFr6Aly0bChOZjrJhfxCHkC9tkYHTf7Nqi5FfVv6v/ocw0wlMXhCJAPRAptMeyP0lM/zEy9AdD/TnTP6Nlf19P5/QmaKZjeZmGQ6iXdkjvISsfDEgf3oIDHlQ+pe9sDPlMhsbMLhlhwkoHYHSS5+Rg+iQCX3b6Ph4xrUco8nH8I7g0Xy4LfFV97Tf+KufoD+zE/AsH9mBt7GMlZC0jeAiOsFpj7EJ5Q4KkmnjOtKUUojNnPTUwHbM37sGnFFxOIkzxcVv0ER7bL5elV7/zaUTVdld+g/Grr1CLVTeZ0emji4mevmrrCq3XVakcCaxum+G62VQ+ryxkhldV7mQCFWBM3Pa7vDubv824352tfEAGHjwoT72/rK4b6HwXr+8uq3UT8NcmX0UT9UPnMz+XZWhzB/2oC/vcbdNX8dpvMRvmZ8auCdPYg++bWEZ+23Zv8iuaR/1xS0wdYHfNJq53Kd/VTGXGXue77WX1toHyNcp8eW+eONhUbt2fZJnAwYzgXV58yW1je7Nt1qOdOkDrDQ+XXn73mxWWwIGhFjUviCnJOJQAzkfPPUhq5VkPnU3OosTDMwZ6kgLSshzSDnBpv1zn+WLdxDfVs7xo9ufqBdzOMa36Z/NLLluGtvp5h03Wd+OLUVhtt5CdY4PNZwf5JCqN8flUuScsMIYaLmII1Ji6KONJGaxmdDynhpv2nY0cFcEErXi/aWCP4NJ8uUQ+a6526OHitOo/cqNCzfNR2uTRmXxABrgk3Bhnai9VnT7HgZ2ZghnPNueifPB1gBfOwaH/nESGSga413mvzOdzzSmgiMPKEjkQEZwMTsvzk6GpfiALNNdTJHNlF+0Al/bLJeNpnXMmTr6KHaCZUAbMgWsKWpclj375/fMqNf0WDZWzORY7XTl29SCxj7lt6Np1X9bh8o3lYf9V/GMG6ea0xgIJiyZJ8YejIhCrvVUsMcxl50xlVuWdA+0m5xrh/WKBtPwYHpsvl+5R93zRdig4Cmmr6ul6XXXZOn1WHNC9hbQa9dHl3ve06/aqHcVKixfnJdYb371BTYMRFfVMghGi1jroJr9WDfbQ70LfpKZIu6mX6ja/CFlebqErL9MmQn5Ibv/s5ZdPS6893DRopnx6CB+1Hc8R9Tnxxl3X5XMp/RYimiaW/srXwD5GfBnK496Lvj/gIObVxqln1JsBFek0+1E3Fovkx9/4N5C15aao4RYHc/e++3FkXdkiq/xQ/jhkLZn7yyp30w74t3mmvu93+UvlTZs72+Iwm9Csm+Eum2fd+AmgdfosBvMD0A55OH67XU9Ty213fbFQ7u6B4pwGdpnbTOO618OpQt4AzQLvImxxrH3WnTiOHlWLv+qwjM7zwwa3XVPEaLgbxz0PP+76ob2BbmTcp7dNP97ThsFPX18XuT9Ub8fzKHmQ4w7iY3oC4LAhr9rflaluRsPuwrrpr4/Elal9/hS8tO9SHke9/y68nzO+Wn/8R3lNxy/DywOQ6dQjnXf4rCquPdKUshGGsWbBly/zUI/v90dV90//Ael8lCs=', 'languages': ['eng'], 'filetype': 'application/pdf', 'category': 'CompositeElement', 'element_id': '7cd838ac423b578976f06c212b381ea1'}
Content: Note:

Intel replaces the following Altera tool names in the Intel Quartus Prime software:

Table 1.

Intel Quartus Prime Tool Name Updates

Altera Name

Intel Name

Qsys

Platform Designer

TimeQuest

Timing Analyzer

EyeQ

Eye Viewer

JNEye

Advanced Link Analyzer

Related Information

Migrating to Intel Quartus Prime Pro Edition on page 74

1.2. Introduction to Intel Quartus Prime Standard Edition Revision History

Document Version

Intel Quartus Prime Version

Changes

2019.12.16

19.4.0

Added programming file generation support for Intel Agilex devices.

2018.09.24

18.1.0

Initial release for Intel Quartus Prime Standard Edition.

Intel Quartus Prime Standard Edition User Guide: Getting Started

Send Feedback

8

683475 | 2019.12.16

Send Feedback

2. Managing Intel Quartus Prime Projects

The Intel Quartus Prime software organizes and manages the elements of your design within a project. The project encapsulates information about your design files, hierarchy, libraries, constraints, and project settings. This chapter describes the basics of working with Intel Quartus Prime software projects, including initial project setup, viewing project information, adding design files and constraints, and exporting compilation results.

Click File > New Project Wizard to quickly setup and open a new project.

Figure 3.

New Project Wizard

After you create or open a project, the GUI displays integrated information and controls for the open project.

Intel Corporation. All rights reserved. Intel, the Intel logo, and other Intel marks are trademarks of Intel Corporation or its subsidiaries. Intel warrants performance of its FPGA and semiconductor products to current specifications in accordance with Intel's standard warranty, but reserves the right to make changes to any products and services at any time without notice. Intel assumes no responsibility or liability arising out of the application or use of any information, product, or service described herein except as expressly agreed to in writing by Intel. Intel customers are advised to obtain the latest version of device specifications before relying on any published information and before placing orders for products or services. *Other names and brands may be claimed as the property of others.The primary function of Intel Quartus Prime software is to provide a comprehensive environment for designing, synthesizing, implementing, and programming FPGA-based systems. It supports the entire FPGA development flow, including design entry (VHDL/Verilog/SystemVerilog), constraint management, synthesis optimization, timing analysis, debugging, and integration with third-party tools. The software is specifically tailored for Intel FPGAs (e.g., Arria, Cyclone, MAX series) and streamlines the design process to enhance performance and efficiency.

In [22]:
from google.colab import userdata
OPENAI_API_KEY=userdata.get('OPENAI')

In [23]:
import os
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

In [24]:
# USING DEEPEVAL SYNTHESISR TO GENERATE A GOLDEN DATASET TO TEST OUR RAG

from deepeval.synthesizer import Synthesizer

# 1. Get random chunks from your vector_store
# Note: most LangChain vector stores have a '.get()' or can be accessed via docstore
all_docs = vector_store.docstore._dict.values() # Example for local FAISS
# Or simply take the first 10 documents for a quick sample
sample_docs = list(all_docs)[30:32]

# 2. Extract context text
contexts = [[doc.page_content] for doc in sample_docs]

# 3. Generate without any prompt configuration
synthesizer = Synthesizer()
goldens = synthesizer.generate_goldens_from_contexts(
    contexts=contexts,
    include_expected_output=True
)

Output()

In [25]:
golden_pd = synthesizer.to_pandas()

In [26]:
golden_pd

,input,actual_output,expected_output,context,retrieval_context,n_chunks_per_context,context_length,evolutions,context_quality,synthetic_input_quality,source_file
0,How do EPE spreadsheet and Power Analyzer in Q...,None,The Early Power Estimator (EPE) spreadsheet in...,[Intel Quartus Prime Standard Edition User Gui...,None,1,2208,[Concretizing],None,1.0,None
1,How does EPE spreadsheet assist in early power...,None,The Early Power Estimator (EPE) spreadsheet he...,[Intel Quartus Prime Standard Edition User Gui...,None,1,2208,[Constrained],None,1.0,None
2,"How do EPE manual entry, Quartus-generated fil...",None,EPE manual entry allows you to input estimated...,[Figure 24.\n\nEarly Power Estimator (EPE) Spr...,None,1,4222,[Multi-context],None,1.0,None
3,How does Pin Planner enable early FPGA I/O int...,None,Pin Planner enables early FPGA I/O interface p...,[Figure 24.\n\nEarly Power Estimator (EPE) Spr...,None,1,4222,[Concretizing],None,1.0,None

In [27]:
qs = golden_pd['input'].tolist()
qs

['How do EPE spreadsheet and Power Analyzer in Quartus Prime assist in pre- and post-design power estimation?',
 'How does EPE spreadsheet assist in early power budgeting and PCB design, considering thermal requirements?',
 'How do EPE manual entry, Quartus-generated files, and Import Data macro collectively complete power estimation?',
 'How does Pin Planner enable early FPGA I/O interface planning and validation using I/O Assignment Analysis?']

In [28]:
res = []
for q in qs:
    print(f"\n--- Processing Query: {q} ---")

    # Store the final result for your 'res' list
    final_output = None

    for event in agent.stream({"messages": [("user", q)]}, stream_mode="values"):
        final_output = event["messages"][-1]
        final_output.pretty_print()

    res.append(final_output.content)

--- Processing Query: How do EPE spreadsheet and Power Analyzer in Quartus Prime assist in pre- and post-design power estimation? ---
================================ Human Message =================================

How do EPE spreadsheet and Power Analyzer in Quartus Prime assist in pre- and post-design power estimation?
================================== Ai Message ==================================
Tool Calls:
  retrieve_context (5dUSvyrMT)
 Call ID: 5dUSvyrMT
  Args:
    query: EPE spreadsheet and Power Analyzer in Quartus Prime for pre- and post-design power estimation
================================= Tool Message =================================
Name: retrieve_context

Source: {'source': '/content/qps-ugs.pdf', 'file_directory': '/content', 'filename': 'qps-ugs.pdf', 'last_modified': '2026-01-07T21:27:21', 'page_number': 1703, 'orig_elements': 'eJzVXF2T28ax/SuofbKrNMx8f+jNZcu5qvKNFWlT98E3pZrPJSokwQCgNusk//32DACaS9IJ5RtsQaUH7QEGJNhnuvt0zwA//f0ubuI27vqPdbh7Xd2pICK10SGZhEI8eIZcIgZJrYizlhFiw92r6m4bextsb+Gav9/5pmlDvbN97Are2Kfm0H9cx/ph3cMRZegKw0Xj8cc69Gs4LMlweN/Uuz5f+dNPGucjxqzon19VIyJUrGSGAtOVucRlNOC77qnr4zb/inf13+Lmw976ePdPOJHqTfwY6jb6vmmf8oDf+WbXw6++G8/u7Dbm43/dd+jw0K32Id2VG+76j9sm1KmOxTwUU4kwQVjdU/KaqteU5HF7+xA/7g5bF1sYRRRm+Wv7+Lf86+/Iiqyqb5vt3rZ11+yqJlX9OlZv3r2p7C6Uv9/C3WyqPx5s2x+66l1bb2P1rnmMbfXNzm6efobPzR/4tC93eV/3m/LLztmjKmhgKiLKQkI8eYy0ZxZp5YkLOFAS3IzsES4KYUyuVCZowkKuRCEMmGNXcBm/ZAbvgaLUbDbNY717qFL9cGhj1a2bx66wF2JXP+yqrocP6ap6Vz2ua7+uwFzVoYvVvhBpM5FdDVc0zaZ7Vaj3ZVLE4VOs94fW+qdpfsSur7e2r5tdB1/eVvAbUmzhJ8M37A99lWdD9/p0XvzBti1c8Cne5/u+Mj+wY5pzhVFUJCKupEROB4609UwI7LRleHbvJlKv2Il7KzVAQvlKX8Fl+JJnx/fDfCCrm3wUM+Kxlx4pHgziUjBwT0JQDEbj6EiUjLyAj04kTHiyOtf0Kl48C2+O7lJ9M3lSdpvvjm7zNrtNVxzvJLZml7zPLnkTex6nSLmVKJpEEKcQZo02GhmDpUvMsyj5jOxRTFbiVUW5XpnMzoSFWpGCqVrJK7iMXzJ7f+qAj0LQbYlOhIipsciwCDJF+4CcpAkpqh2VAXtr5Zw0cL4iYFbGRxpGLNhodght7Aou45dMw3MF8t2Q1961Tf7im4ixzHPMHEeYR404EwQZQjACmrSg3ns+a4ahRKwUGFrx0fAj1hMRID3IFVzGL5mYkYpvm52P+9t8RBNBJIPYxHgWg4EkpB0kGq0dl1J4g5mYkwptsjqnmA9icMKUrnTGjJoVv4LL+CVT8W4DN5LtXDLJezBDFoXvY3fY9LclEcFo4ooo5L2miHsZgBRGEBNOSKe9pWJOmc44W1FI6WaMXiOmZHQKpnAWXud4GL9kZj7U28NmkACfQ0cSQnjLBJIBMgo4CoOYFQ0iLBiWsDOM+TnpwOXQMWZNeIpRTBYdfIG/lJj1drsfzF2YuYmRKJhQgUjkgwIHcR5UFk8W+RQjxSC4KJ0zvTMtsqoihg2NhhFTQoa6lYEnXMHD+CUz8l/VQ7WuYnVbN8HY4CWnGkVhA2hdHZCFuIWYD9pIxoLHc/aCjiyoZyyQqTt0tPo5Vgtnob6tTjSeyJyvk+ZQaUgVEcx7gYJlgRDBAvdzVhrTnJd4tO6IlRzqwskHznEZv2Tr/1A11eO5D/zbzgmzypVaPYWYfcEZpC3mKMVEk1E+kjArG2YUR3QQUxMmfIVLlY4HcXWOy/gls/Gm6qq+qj+LC2OgylARsjT24BmCwV9BeiSN1jY5lXSYs4NybvsJSzV4ymT7c1zGL5mLbWUzF+Afu+qbysO/Q9XCMV89fRY/UoJ6ojohTzkDPSU4Mk4rJJRSNHkbk00z8gNFZ+GDsdEXRiz4ihcMkYpewWX8kvl5viAwdEvKKsLtfROsOJUhUJC6CcJYjBZZojH8JTFkdY0Z13PWhHJoR5kxqYyYYTyGNbhEXOJh/JKpGaXuh7ICcFsNSKwPIKKQdzJL3MiRjk6h4Jk1NAgajZq/DcygxuMnbWAGTlCYEQznoHWBy/glM/F8qaa3bhOrTd3140rN2Az2satc7B9j3P2GtbjVZ4VDpbUU3ESEhXAgHZRHDiuobTilJjAZjZ5/SZVlfn9ZdGFiTF6E4hz8LnAZvmieC7M3rrlYKORpkglRSNaIg6JGRuZaX3JuNItaMfYCzjZxMOHJ6Fyr3IW8wIsn4UUWtaWEmp87j5hWkLOYj8g5IC8mqbzULkQ+b6QcIp9kQ7dswgqP2BR5cYHL+EWTt7at9X0E/vra30QFM4ELKxmSICPAjxhFRkNNGk20KvnkEpu1IwBKmp5QMeHJ9Iyy3Bm7wIunArzmNvtTmoSQJos2iGMirx3T6JEOwlqhJMFuztUVZlheTfnF/iOe7C2YLHHtHC/e/v+hSBW41okHjJySGnFlJNI8SJQSE0IYq6AUmpEeM3qDGRZURqjlAAlnJS6d4zJ8yeT8zzqLtCZvpfks3RUIo1ljIUqkzU3k3NYHjwk+r9VHCel11qV6PtQ2Ex0TnuxP4QS+ghfPxze7p6oHD7ltv4TgkbnAQPKyiLgWCpK3hTJHMGYwc564ORchGSRjc0LChCejc1qWti7w4kl413Q9SvVtVb+V1ApiMCioBLW+whhZySWiRpEojMdJxxfwBEPGqn/AnIxymEFNoi7xMH7JJPyh6ePr6vumrfYjHWd7/V6VPYAPsc/FJiitqh2WJavHul/PUmwmrKMHTYyMtZCCfKRIR+GRp0lTbEjybs6VsyHncDoKhBGySRqr0gm9wHTp+uBDk/pH20bg768HuIts8NvaPNFRFhh8H4WEgzjBHGkjAsS/KAIFT1CzrmROrjYRMmF2VMg8X3KBl8/Ivo02dOsIvrVvm4fWbm9b06SB2IAFstRliRYdMjFE5LUWISSXVxDmz0dHPiY82V/kPRdX8OL5uP+VWNaNnnOjfmbYChMQVcAQJ5oii4lEjBNnOEuQruZs00zR6pl+5nzSy8CJvILZ0qXCtBv2trZ0UhZzTlC0AvSaNR5Zl0UzSATNFLeEvIBUOHIwYX4UyeIZKRNePAn/HUN9uDFEWagZcRKIhLyFklqoIq0iyAlPqdBaq1kf4jiGpOeS+WhyLnWuGy/wF0JBriQ/xfapWoNlblszg8gTqWOIglAGl2ASORMNki4HJWq5i3NuDxvDkBDDktgI5bgRgGSzX8Fl+JLZ+A4sNTzIcpuQUh5klIrwRVTpcb1MM4yEAw3lLYtOzNl6nALRRMOEzZTIBSlecI4Xz8P72DWH1sfq0MG46aGj2FX/e4DPo9W3m8b/5Znunc682X2q22ZXdvZtKrjnUA8PK43n75uHhw1IZvi0U4Z/qLv+bTbFteyjbWBOOCQtB1fjUMfYGBMyRjKVklSMzbrvbwx1E8kjFmR0LoHLusw5Xj7JU7dgelLt33L7AUYBqdZDrVn3T3BdsqVwvZH79/EBaIYqtm/trkvwxyZ+AnH41fv7H76uul/26U4F8VfNPmO7+frWuWIlwSzyHJY9hkrXReSocchjpS2mXmD+AnNFEDnuyh0xJ1Pvu+yHu8Bl/BcxV/4lS9cnSg1xYw9k75oQq6at4J7z7PkN5GIfXfAGKel53iEfkQ46IiG1ZUTHyML8OVcIfFoJCKGmzjkvVF9gvHAFVHIu/PSbk24wQXIZHHJlk4pRERkpKBLKiMB1FDHNuV1otDtoG3pCgxz3+1JKcgq+xPSLaBven6yW/4a1JiEdZlw6xJRTiCe4CeugSiAxCOoUaFY665YGMDYDYys8bM4+4nGzdn7wkF/DeOGbs0f3qD5ZqBFcznyfalBHyW7rzdPn9WKpBmHqlEeUGoY4JgxpAbrVKGF1sARi2ZyF3ChRj1FsxBKPYYvJ0n09x8sPY/dNFh39OrZb+H/ouIe66+r9kK0m/TkO6PKDJ34cd3YuPMGdnp/8MSXk1/X+1z/620NbnigOrX3cValtttWnZpM3/1XdYb/f1M83Af6rTCcTpjyJlDczQ6YTSSLjTEBEGSKZDMLpF1ggO06SEUuqx3dsMJqD7jn+MifJ/3diTCff/u7H6yeGgyVqFJ29rmNrW79++tWBrkjwPFGuDzmdfDDcl+Gh2dp6d+sMoxSkMDcSUYdBKDsukSbEIu88jprRoMK8m0aGGQUTB5/OMIhGfGhx01xEXeAyfskz7Bgmvto1OzTOtK8vebuVJ29sDFwmFAmFjE7yNp8gNDI+eaMSlsK/QCSQ55FgUrlc6xIJLvDSI8F3QwYvgRk8aAjdN8dn6qKNzhrkpJOIMyKQMQYqkeSlkF6wGOdfUJVSnnb/pKbT6x1YvuACy6W/UOfkZR1542huEvgIUqod3ae872YMwXCPza68c2e4IEXbH9obt9lbkRi32CDMiBo0mImMoOTz4isNLs2683fSXBN/EzZ4fHJUFdl8gRdP4Nud3xwgy0H5cvKiomkXcL3zQ0PpmMfg3rrDdj/lMRjUxSOTn7nFAVzP8OARIZpAPnMBZHXQyAmtVCKGJE1fIE5OlE5YsQHnhZBrePGUQlmaicu0hs8iRMpgwbssMlI78DHnkeOYIZKSMRAxjcJmzlIUs2xgxeTQB5gwHx9dIZJexWX8kgn5EHeh+j7G4Kz/yykj3zdND1dcoYJJyzlOEXEZ8lNFHKpNwRUSDOSEcTRwP+deeQq+QLJp6bjdZMR8fNmU4PgqLuOXTMW1rQ0fersLtg3Vm6H5XZV3GP3+UIf4+vwFU7nJ8yNEv23984Um/HU2U4AsRahGmkpQ7sRRUISYFvkuKWZazvoAvmDlkW8l6MjWhM0v7OFrmC78VWHiNvNbTjyJWKEIxkbcSoGcVQZpLED8aiidZjV/XtOFQ2JcbJqgGdee2FW4wOe9+anpyerMNW7V4STJAFwQsH5+XtUxSPhUU5S0FdIAUZbZOcmAkKVytTMI7RGqUXeP1j+DZfCSyZCaCSyrf1QUE73KD9PwUzr+tPNguYemrX+OYUj+f/4/lcNrHg==', 'languages': ['eng'], 'filetype': 'application/pdf', 'category': 'CompositeElement', 'element_id': '9be688a11cf3fa41591a58de810afc6f'}
Content: 1.1. Comparison of the EPE and the Intel Quartus Prime Power Analyzer

The following figure shows the design stages in which you use power analysis tools, and compares the accuracy of the estimations for different input types:

Figure 1.

Estimation Accuracy for Different Inputs and Power Analysis Tools

User Input

Quartus Prime Design Profile

Design Concept

Placement and Routing Results

Simulation Results

Design Implementation

H g h e r

i

L o w e r

E s t i

m a t i o n A c c u r a c y

Power Analyzer Input EPE Input

Design Stages

The following table lists the differences between the EPE and the Intel Quartus Prime Power Analyzer.

Table 1.

Comparison of the EPE and the Intel Quartus Prime Power Analyzer

Characteristic

EPE

Intel Quartus Prime Power Analyzer

When to use

Any time

Post-fit

Note: For post-fit power analysis, you get better results with the Intel Quartus Prime Power Analyzer.

Software requirements

Spreadsheet program

The Intel Quartus Prime software

Accuracy

Medium

Medium to very high

Data inputs

Resource usage estimates • Clock requirements • Environmental conditions • Toggle rate

Post-fit design • Clock requirements • Signal activity defaults • Environmental conditions • Register transfer level (RTL) simulation results (optional)

Post-fit simulation results (optional) • Signal activities per node or entity (optional)

Data outputs

Note: The EPE and Power Analyzer

outputs vary by device family.

Total thermal power dissipation • Thermal static power • Thermal dynamic power • Off-chip power dissipation • Current drawn from voltage supplies

Total thermal power • Thermal static power • Thermal dynamic power • Thermal I/O power • Thermal power by design hierarchy • Thermal power by block type • Thermal power dissipation by clock domain

Off-chip (non-thermal) power dissipation

Device supply currents

Estimation of transceiver power for dynamic reconfiguration features

Includes an estimation of the incremental power consumption by these features.

Not included

Send Feedback

Intel Quartus Prime Standard Edition User Guide: Power Analysis and Optimization

5

1. Power Analysis

683506 | 2018.09.24

Source: {'source': '/content/qps-ugs.pdf', 'file_directory': '/content', 'filename': 'qps-ugs.pdf', 'last_modified': '2026-01-07T21:27:21', 'page_number': 41, 'orig_elements': 'eJzNWluP2zYW/ivEPLXA0CNedGHestukCLDYnd1MUSyKIqB4sdXKkivJM3Gz/e97Din5Np5kpgtn/eYjH5GHPLfvI/XTpytXu6Vrhg+VvXpFrpLMGC+Zp6nnnMrUaqp5JqlRSkuVOZ2q7OqaXC3doK0eNLzz6cq0bWerRg+uD3KtN+16+LBw1XwxwJNc8VkCL43PHyo7LOBxxuLjVVs1A7750095eMLTbJb/fE0mMUujyLiY8RNyUIcHV/2mH9wS13FbfXT1+5U27uoP+MNXtftgq86Zoe02qHBj2maAdV+N/zZ66fD5b6ueruf9bGX9VTC5Hz4sW1v5yoUN4gnPaMJokt9x9ornrzhDvZWeuw/Nelm6DrQkw0kH9xFXf/W2mq87R7icoeawWYWJ7qqhDsYdu0BYIy13inLPNZWJklQliabC2txr5YvcndMFTOQHPpjkadOFzGfFCfnCnfBGd/WG3LYPriNv+qFaajCCfPPm9s235P2qc9r2C+eGZ3mIycxK7hh1nCVUloZRxfOcKl8mAmzz3iXn91BayJna81CWyOiRlOez7LEc9S/XQ/9u18Tohix1s9Y1OAumBWfhBhJYe0uGhSPgL9Lv3HVNwInr3oX/3oF+Tf651t2w7sltVy0d6Vs/PGjIPnh/7hrXwf4T6+4r40jn+nbdwY+q8W0HAVG1DYFfBBwA87q+mjcHKft33cH71b27Q5NPBIZWAgpkUkJgGEmlURAYmZDUWcfSokwsK75C6mYsnaX7gQGpGQIlFWzGTshB/3ID4659YUxEJfzryNM9xMsKY6Bq5sR37re1a8zmGoJjPq9BDX1wTXRjSQtvd2SlO1gWDNY/igvyzqNMbEuadiALfe/gReI+Vn0YPaqBLbHWxAiNCyStf2QYBrGFJe3PES2B95r9FX1u6dt9elnYFrmBcmYdTQsOYcuLBDoOK6grmTbcZj7N+FcI2yw/6DiZUjMRwpSpmTwhB/3LDdsxQJ6IDCxcGgNsqEJgm3a5qiHU7Nb5m7Eevri8hcA42e7eworJN7PhIyTJzPT33+J7uu/BsjAdxN9oBxp6IsBeFlcm0ywDOINF0EI51CWASZ1ToRMrjNSC6fODyVzwWO0mUUVRJGKWnpL5RXfJU1HwfoBCoTtL3tgqNLEfenD79+vKulfkezcEb4JSB+H1LIDjFQAbkXiqUl9QCQiHlklW0NwyXlrhndPlGR0ncxFdlc04umaSpYhyKvhJOehfruveOyjnb52zpTa/7vvhbdtCeT/liCRXKi8AS9gUCIHMSknLHLzBZJowlxuls/T8GZTyWHgncazDRTJTJ0RUvlwnyOR5O++zkhWClZQlkAfSGkfLTOTUGpaVpbZ5KtQZdx42EyE+jx1xlNTYH1MR8PyRyC+tG/L9fRcz8l1sfLe1bhqoSPt++Bt0oHdo9SlQDfWmEGVKs8QLKgsjaMkyTplShulEy9ydMwfi3gPbZTtPQCIECbrbTDwSg+7leiIrgLKn5D+EJwCkYMEs23fFD42BXZu3XfW7s091dikLaw0wG58X4BNRWFqwzFLtXe6Zlyrn58wOKH/4SBUjAY4iy8d0SUWBAPFYDuqX65e7E3i+aky9BkAYAeBy1XYD+Q4ZwFKbDimAHhBD9qPGPpEFLDcBuAD7ApfodNN7pDOPtUdGsQ/2jjjOg24GBIwTIA027HDqlqNNs3yZr8zIW0Cl7qNGzAl0xyPLqcIy9wFosP+ktY+o32SMtvZzND8sDQfYovJTuGrVtb9AKMAIMEUPUdCTtoEFAm5HC8GQ1kfC5td1vQXuR2QVpwFzAjLT9WPmhybjlo4O81XUevnpQ5pwa53zNDEuARrHMgALilGTW6mUN0mZfIWkZIUcTx9GWYkoC16clIP+5ablqcCIvOo1OGrzO7zyHEgNmMHwQkvKTG6oTIBoq1SBr5TJRJoUPjHy/M7hiYxgbZJlOpXIJBylH8tB/3Kd8zpUjJD0I38+PEB5Doc+dCYWuJXrsFJAnm9HXbX9QH0F1TZoa9QG2ozaZuHMr2H0+B+svl8vV6E+LFvg5tqYNRLzejMjWOSPJoQqc19hjceyNapOx0ZjjQkD47lWv+5iYYS6jydUSygVWNj79WoFBaeultUQ3oLRYOblSxm7LESRIk/nZcaoZJmjWjNPoapI5SVT0p8Ta01RmeYHJYRnWZS5DCfZj+Sgf7lR+i9XazzZebdrQM+rGV5ZkzJFmVOSSpUpqqTVNJGlUKXmxuTiK3gD2PdBzShGOiiwcp+Qg/7/1xt11fwaFvHpqsdzjw9VY91HeJBcf+lKCNPpKEN/dCW5Bf/iyOuuxncXw7B6dXPz8PAw0zXUID2DUnGDaQjI4Cb2+P7GTaPeQAbTkMUr2PfZL/3q6o+fvxA1f8q8L8ZUmgsIKZvTJFOKQiBBhmeppaX1tpTOCiHPedYb+RNXaiZ3dEowFkWuGHadYzmqX25+i1kxC7Q23BJgj+k8GEbe3fyD3FZN/7wzN2eShAtPU+1zSHbjqRZCUV0a4SHZmRdnPYSPyS04Pyi90A6inIoUr3kfyUH/cl3zLvCSzXTo7pr7qmsb3Pb+mry9/f71+A9yoonfrNCT2M+HdkVrdw+IIWiiO1fgTuJCZoLmwtUrUrZ49LobpnTzEcrf/vUv08SYttEJEQPgWEavdFnVQAxC87fjSFGNzPH4FuoY/NdGrjKaG+gDcJkaL68cWkTq1kxdf3t3hQEXXsXz/Xlc8pb27NtMBqeXwKKcwY0OMCTMBANTMOQ6QpuDWZbrfoB1knvXBedM3CW+V4PncbpgTAdDIGTZv6nQ921lD20wC93MXf8ytKLyFDC0SqlLc+iPSampTngKmLrIZcq9lvycx9RTiqjsoD9Kvr1eVXgieixH/ctNmeke3gCtBiQKZLdzCCwb3W2moAiFDnQing5uf6iGxdMYuxrP/SAwS+cRFYeDBUyudhUPHiJJN61116TUeB0K4LefrjYwYaqpsvbkm35tFhDaAHEBY29i+sB0O5VvwzPM/ZgPOADe+MKuhlzY3ehGN7ws9Jywzhd5QpnQSOd0Dh1U5tSUUoqUZ6Ys3flDT4rpyjTKaZJM9C3HUDuWo/7lht7dE+GDvnu9LWMR+SD7CtSr39KhE7Vwr/gFRjQitF3JAnQ4d0MMYd2ZRTXAytedm5EpD8IFPBLIp6yAinav68pitoAO7Ua4vz93MDGw0ZhVEHthr6CNLKBEzheYVPGLhVAPgRRCDEPB/hFnnwgunoPt8dtpDZ+7Gb5+0uxujXu0HlpkJCYcWE1lvBqGyIS369pu8f6ilnhECS8efmqxl2LogelaGtpm1+GyYVn6xaW+ZKnUGgo8kxJgq+SWFh6YUeHzVIqsLIqyOH++pQBM99ERtJ0JDWUn5aB/ufkWKcbo9cPIu57qdAjY6TT2oEiHB2Fdu8whC90fHNXqcors/6GUx7ne3cLEnetPfiZzUOhPpiAUbEBTMPZmsno/Vnf5Hs+KqsNlbLvbyMqq3T0W8bBB+IHnhPr2eh2kUARWiEAHXdX93oaMG364HUd1Z9uEd1h0fA1DI6bl9pIAUzGOtjvoflGWcZaZPNUp9YVGcgi8UHlZUlbmiee5TVJrvkKWAcfYB1RZquL9Wiok0sFjOepfbpbdHQXFXuzvQFOM7d0XZ8TZCmy9Jg+LCtOjrtuHeFeAR47bJhIvS4gBQN4udxkS4mLqWaeCC1bv42fJi/YhDNmCbSYGpl83ZtdCxxFboD1gSMwxzKEY15gAEGqQ/vCjgbpAcCcjuuohugymIdq4P/lo/mfTFQcAhXAxst0veBbf2sudQMke5941lhRQM11VTu0ekrp3Jl4AHXslGtUTIIjDWtcBSxzbEyzB6xlcKJTIvj16FDAG3pXFN2Fe2LexMwY7bTzAjc38T2Soz3KXlhB/pcozKnOWUiW8oLmSHj8VVxn7Crgzy9TBzWsOODP2PV6Ej0CO5Kh/uRkarxG2h/rhRH3TYPRVW/bduAco/BOasXsF+aHTqxW8j0Zeb68adpqNG2r8wm7vZiFgsmm6bREIn2g9DXbb5RIse+EXyV6r0mWKculKKgWXtOBFTlWSpYKXiS2z/JzxkogQD9OXXJM8fbnFMn5SvrwvuQ7i5Ytfcv38Xw7RFMU=', 'languages': ['eng'], 'filetype': 'application/pdf', 'category': 'CompositeElement', 'element_id': '15695c5a7024ed0607a13918891f651a'}
Content: Figure 24.

Early Power Estimator (EPE) Spreadsheet

You can manually enter data into the EPE spreadsheet, or use the Intel Quartus Prime software to generate device resource information for your design.

To manually enter data into the EPE spreadsheet, enter the device resources, operating frequency, toggle rates, and other parameters for your design. If you do not have an existing design, estimate the number of device resources used in your design, and then enter the data into the EPE spreadsheet manually.

If you have an existing design or a partially completed design, you can use the Intel Quartus Prime software to generate the Early Power Estimator File (.txt, .csv) to assist you in completing the EPE spreadsheet.

Intel Quartus Prime Standard Edition User Guide: Getting Started

Send Feedback

40

3. Design Planning

683475 | 2019.12.16

The EPE spreadsheet includes the Import Data macro that parses the information in the EPE File and transfers the information into the spreadsheet. If you do not want to use the macro, you can manually transfer the data into the EPE spreadsheet. For example, after importing the EPE File information into the EPE spreadsheet, you can add device resource information. If the existing Intel Quartus Prime project represents only a portion of your full design, manually enter the additional device resources you use in the final design.

Intel Quartus Prime Power Analyzer

After you complete your design, you can use the Intel Quartus Prime Power Analyzer to perform a complete post-fit power analysis to check the power consumption more accurately. The Power Analyzer provides an accurate estimation of power, ensuring that thermal and supply limitations are met.

Related Information

Early Power Estimator and Power Analyzer Web Page

3.8. Plan for Interface I/O Pins

In many design environments, FPGA designers want to plan the top-level FPGA I/O pins early to help board designers begin the PCB design and layout. The I/O capabilities and board layout guidelines of the FPGA device influence pin locations and other types of assignments. If the board design team specifies an FPGA pin-out, the pin locations must be verified in the FPGA placement and routing software to avoid board design changes.

You can create a preliminary pin-out for an Intel FPGA with the Intel Quartus Prime Pin Planner before you develop the source code, based on standard I/O interfaces (such as memory and bus interfaces) and any other I/O requirements for your system.

The Intel Quartus Prime I/O Assignment Analysis checks that the pin locations and assignments are supported in the target FPGA architecture. You can then use I/O Assignment Analysis to validate I/O-related assignments that you create or modify throughout the design process. When you compile your design in the Intel Quartus Prime software, I/O Assignment Analysis runs automatically in the Fitter to validate that the assignments meet all the device requirements and generates error messages.

Early in the design process, before creating the source code, the system architect has information about the standard I/O interfaces (such as memory and bus interfaces), the IP cores in your design, and any other I/O-related assignments defined by system requirements. You can use this information with the Early Pin Planning feature in the Pin Planner to specify details about the design I/O interfaces. You can then create a top-level design file that includes all I/O information.

The Pin Planner interfaces with the IP core parameter editor, which allows you to create or import custom IP cores that use I/O interfaces. You can configure how to connect the functions and cores to each other by specifying matching node names for selected ports. You can create other I/O-related assignments for these interfaces or other design I/O pins in the Pin Planner, as described in this section. The Pin Planner creates virtual pin assignments for internal nodes, so internal nodes are not assigned to device pins during compilation.

After analysis and synthesis of the newly generated top-level wrapper file, use the generated netlist to perform I/O Analysis with the Start I/O Assignment Analysis command.

Send Feedback
================================== Ai Message ==================================

The **EPE (Early Power Estimator) spreadsheet** and **Intel Quartus Prime Power Analyzer** serve complementary roles in power estimation across different design stages:

### **Pre-Design (Early Estimation) - EPE Spreadsheet**
1. **Manual Input or Auto-Generated Data**:
   - Designers can manually enter device resources (e.g., LUTs, FFs), clock frequencies, toggle rates, and environmental conditions.
   - Alternatively, Quartus Prime can generate an EPE file (`.txt`/`.csv`) with resource estimates from a partial or incomplete design.
2. **Purpose**:
   - Provides a **rough estimate** of power consumption early in the design cycle.
   - Helps identify power-critical areas before detailed implementation.
3. **Accuracy**:
   - Moderate accuracy due to reliance on estimates (e.g., assumed toggle rates or resource usage).

---

### **Post-Design (Accurate Estimation) - Power Analyzer**
1. **Post-Fit Analysis**:
   - Uses actual placement and routing results from Quartus Prime to calculate power.
   - Incorporates post-synthesis data (e.g., signal activity, register transfer level (RTL) simulations).
2. **Detailed Metrics**:
   - Outputs precise values for thermal power, dynamic power, static power, and off-chip power.
   - Includes breakdowns by clock domain, block type, or hierarchy.
3. **Accuracy**:
   - **High accuracy** (medium to very high) because it reflects the final design’s physical implementation.

---

### **Key Differences**
| **Aspect**               | **EPE Spreadsheet**               | **Power Analyzer**                  |
|--------------------------|-----------------------------------|-------------------------------------|
| **Timing**               | Pre-design or early design        | Post-design (after synthesis/fitting) |
| **Data Sources**         | Estimated resource usage          | Actual placement/routing data       |
| **Accuracy**             | Medium                            | Medium to very high                 |
| **Use Case**             | Initial power budgeting           | Final power validation              |

By using both tools sequentially, designers can iteratively refine power estimates, ensuring compliance with thermal and power constraints throughout the design flow.

--- Processing Query: How does EPE spreadsheet assist in early power budgeting and PCB design, considering thermal requirements? ---
================================ Human Message =================================

How does EPE spreadsheet assist in early power budgeting and PCB design, considering thermal requirements?
================================== Ai Message ==================================
Tool Calls:
  retrieve_context (fGXpKYhw4)
 Call ID: fGXpKYhw4
  Args:
    query: How does EPE spreadsheet assist in early power budgeting and PCB design, considering thermal requirements?
================================= Tool Message =================================
Name: retrieve_context


In [29]:
(res)

['The **EPE (Early Power Estimator) spreadsheet** and **Intel Quartus Prime Power Analyzer** serve complementary roles in power estimation across different design stages:\n\n### **Pre-Design (Early Estimation) - EPE Spreadsheet**\n1. **Manual Input or Auto-Generated Data**:  \n   - Designers can manually enter device resources (e.g., LUTs, FFs), clock frequencies, toggle rates, and environmental conditions.  \n   - Alternatively, Quartus Prime can generate an EPE file (`.txt`/`.csv`) with resource estimates from a partial or incomplete design.  \n2. **Purpose**:  \n   - Provides a **rough estimate** of power consumption early in the design cycle.  \n   - Helps identify power-critical areas before detailed implementation.  \n3. **Accuracy**:  \n   - Moderate accuracy due to reliance on estimates (e.g., assumed toggle rates or resource usage).  \n\n---\n\n### **Post-Design (Accurate Estimation) - Power Analyzer**\n1. **Post-Fit Analysis**:  \n   - Uses actual placement and routing results from Quartus Prime to calculate power.  \n   - Incorporates post-synthesis data (e.g., signal activity, register transfer level (RTL) simulations).  \n2. **Detailed Metrics**:  \n   - Outputs precise values for thermal power, dynamic power, static power, and off-chip power.  \n   - Includes breakdowns by clock domain, block type, or hierarchy.  \n3. **Accuracy**:  \n   - **High accuracy** (medium to very high) because it reflects the final design’s physical implementation.  \n\n---\n\n### **Key Differences**\n| **Aspect**               | **EPE Spreadsheet**               | **Power Analyzer**                  |\n|--------------------------|-----------------------------------|-------------------------------------|\n| **Timing**               | Pre-design or early design        | Post-design (after synthesis/fitting) |\n| **Data Sources**         | Estimated resource usage          | Actual placement/routing data       |\n| **Accuracy**             | Medium                            | Medium to very high                 |\n| **Use Case**             | Initial power budgeting           | Final power validation              |\n\nBy using both tools sequentially, designers can iteratively refine power estimates, ensuring compliance with thermal and power constraints throughout the design flow.',
 "The EPE (Early Power Estimator) spreadsheet assists in early power budgeting and PCB design by providing a framework to estimate power consumption during the initial design phases, which is critical for addressing thermal requirements. Here's how it works:\n\n1. **Early Power Estimation**:  \n   - Designers can manually input parameters like device resources, operating frequency, and toggle rates into the EPE spreadsheet. This allows for preliminary power consumption estimates before the full design is finalized.  \n   - If using Intel Quartus Prime, the tool can generate an EPE file (.txt/.csv) from the design, which can be imported into the spreadsheet for automated data transfer. This integration ensures consistency between the design and power estimates.\n\n2. **Thermal Planning**:  \n   - The EPE's power estimates inform PCB-level thermal design decisions. For example, high power estimates may require larger heat sinks, improved airflow, or additional thermal vias on the PCB.  \n   - By identifying power-hungry components early, designers can allocate power delivery resources (e.g., voltage regulators) and cooling solutions proactively.\n\n3. **Iterative Refinement**:  \n   - The EPE serves as a baseline for power budgeting. As the design evolves, updated data from Quartus Prime can refine these estimates, ensuring thermal requirements are met as the design progresses.  \n   - The tool’s flexibility allows manual adjustments, accommodating changes in design scope or component selection.\n\n4. **Guideline for Power Supplies**:  \n   - Early power estimates guide the selection of power supplies and voltage regulators, ensuring they can handle the estimated load while meeting thermal constraints.\n\nIn summary, the EPE spreadsheet enables designers to address power and thermal challenges early in the PCB design process, reducing risks of late-stage redesigns or thermal failures. For precise validation, the Intel Quartus Prime Power Analyzer is used later in the workflow.",
 'The EPE (Early Power Estimator) spreadsheet, Quartus-generated files, and the Import Data macro work together in a streamlined workflow for power estimation in FPGA designs:\n\n1. **EPE Manual Entry**:  \n   - Used when no existing design exists. Designers manually input parameters like device resources, operating frequency, toggle rates, and environmental conditions into the EPE spreadsheet. This allows early-stage power estimation based on estimates.\n\n2. **Quartus-Generated Files**:  \n   - If a partial or complete design exists in Intel Quartus Prime, the software generates an EPE file (`.txt` or `.csv`) containing device resource usage data. This file captures accurate resource utilization from the design, replacing manual estimates.\n\n3. **Import Data Macro**:  \n   - Automates the transfer of data from the Quartus-generated EPE file into the EPE spreadsheet. Instead of manually copying/pasting resource data, the macro parses the file and populates the spreadsheet, ensuring consistency and reducing errors.\n\n**Collective Workflow**:  \n- For new designs: Start with manual EPE entry.  \n- For existing designs: Use Quartus to generate an EPE file, then import it via the macro into the spreadsheet.  \n- This combination ensures accurate, efficient data integration, enabling precise power estimation early in the design cycle. Post-fit analysis can later refine results using the Intel Quartus Prime Power Analyzer.',
 "Pin Planner enables early FPGA I/O interface planning and validation through I/O Assignment Analysis by allowing designers to assign and verify pin configurations *before* finalizing the HDL design. Here's how it works:\n\n1. **Early Pin Assignment**:  \n   - Users can assign I/O pins (e.g., selecting banks, voltage groups, differential pairs) directly in the Pin Planner, even while developing the top-level HDL wrapper or during early design stages. This avoids late-stage constraints.\n\n2. **I/O Assignment Analysis**:  \n   - The tool runs validation checks to ensure assignments meet device/PCB requirements (e.g., voltage standards, loading, slew rate).  \n   - It generates a synthesized netlist, which can be used to identify and fix issues (e.g., timing violations, conflicts) early in the process.\n\n3. **Iterative Refinement**:  \n   - Designers can repeat the analysis after modifying assignments, ensuring continuous validation. This reduces the risk of errors in later stages.\n\n4. **Integration with PCB Tools**:  \n   - Pin assignments can be exported to PCB design tools (via .qsf/.pin files) for validation, ensuring consistency between FPGA and board layouts.\n\nBy enabling early planning and validation, Pin Planner helps optimize I/O performance, reduce design revisions, and improve time-to-market."]

In [30]:
(res[0])

'The **EPE (Early Power Estimator) spreadsheet** and **Intel Quartus Prime Power Analyzer** serve complementary roles in power estimation across different design stages:\n\n### **Pre-Design (Early Estimation) - EPE Spreadsheet**\n1. **Manual Input or Auto-Generated Data**:  \n   - Designers can manually enter device resources (e.g., LUTs, FFs), clock frequencies, toggle rates, and environmental conditions.  \n   - Alternatively, Quartus Prime can generate an EPE file (`.txt`/`.csv`) with resource estimates from a partial or incomplete design.  \n2. **Purpose**:  \n   - Provides a **rough estimate** of power consumption early in the design cycle.  \n   - Helps identify power-critical areas before detailed implementation.  \n3. **Accuracy**:  \n   - Moderate accuracy due to reliance on estimates (e.g., assumed toggle rates or resource usage).  \n\n---\n\n### **Post-Design (Accurate Estimation) - Power Analyzer**\n1. **Post-Fit Analysis**:  \n   - Uses actual placement and routing results from Quartus Prime to calculate power.  \n   - Incorporates post-synthesis data (e.g., signal activity, register transfer level (RTL) simulations).  \n2. **Detailed Metrics**:  \n   - Outputs precise values for thermal power, dynamic power, static power, and off-chip power.  \n   - Includes breakdowns by clock domain, block type, or hierarchy.  \n3. **Accuracy**:  \n   - **High accuracy** (medium to very high) because it reflects the final design’s physical implementation.  \n\n---\n\n### **Key Differences**\n| **Aspect**               | **EPE Spreadsheet**               | **Power Analyzer**                  |\n|--------------------------|-----------------------------------|-------------------------------------|\n| **Timing**               | Pre-design or early design        | Post-design (after synthesis/fitting) |\n| **Data Sources**         | Estimated resource usage          | Actual placement/routing data       |\n| **Accuracy**             | Medium                            | Medium to very high                 |\n| **Use Case**             | Initial power budgeting           | Final power validation              |\n\nBy using both tools sequentially, designers can iteratively refine power estimates, ensuring compliance with thermal and power constraints throughout the design flow.'

In [31]:
eval_pd = golden_pd.copy()
eval_pd['actual_output'] = res
eval_pd

,input,actual_output,expected_output,context,retrieval_context,n_chunks_per_context,context_length,evolutions,context_quality,synthetic_input_quality,source_file
0,How do EPE spreadsheet and Power Analyzer in Q...,The **EPE (Early Power Estimator) spreadsheet*...,The Early Power Estimator (EPE) spreadsheet in...,[Intel Quartus Prime Standard Edition User Gui...,None,1,2208,[Concretizing],None,1.0,None
1,How does EPE spreadsheet assist in early power...,The EPE (Early Power Estimator) spreadsheet as...,The Early Power Estimator (EPE) spreadsheet he...,[Intel Quartus Prime Standard Edition User Gui...,None,1,2208,[Constrained],None,1.0,None
2,"How do EPE manual entry, Quartus-generated fil...","The EPE (Early Power Estimator) spreadsheet, Q...",EPE manual entry allows you to input estimated...,[Figure 24.\n\nEarly Power Estimator (EPE) Spr...,None,1,4222,[Multi-context],None,1.0,None
3,How does Pin Planner enable early FPGA I/O int...,Pin Planner enables early FPGA I/O interface p...,Pin Planner enables early FPGA I/O interface p...,[Figure 24.\n\nEarly Power Estimator (EPE) Spr...,None,1,4222,[Concretizing],None,1.0,None

In [32]:
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
from deepeval import evaluate

# 1. Define the Similarity/Correctness metric
similarity_metric = GEval(
    name="Answer Correctness",
    criteria="Determine if the 'actual output' is factually correct and semantically similar to the 'expected output'.",
    evaluation_params=[
        LLMTestCaseParams.ACTUAL_OUTPUT,
        LLMTestCaseParams.EXPECTED_OUTPUT
    ],
    threshold=0.7
)

# 2. Create test cases from your DataFrame
test_cases = []
for _, row in eval_pd.iterrows():
    test_case = LLMTestCase(
        input=row['input'],
        actual_output=row['actual_output'],
        expected_output=row['expected_output']
    )
    test_cases.append(test_case)

# 3. Run the evaluation
eval_res = evaluate(test_cases, [similarity_metric])

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=True)...

Output()

INFO:deepeval.evaluate.execute:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute:in _a_execute_llm_test_cases
INFO:deepeval.evaluate.execute:in _a_execute_llm_test_cases

======================================================================

Metrics Summary

  - ✅ Answer Correctness [GEval] (score: 0.9851952798209368, threshold: 0.7, strict: False, evaluation model: gpt-4.1, reason: The actual output is factually correct and semantically aligned with the expected output. It accurately describes the roles of EPE manual entry, Quartus-generated files, and the Import Data macro, matching the expected workflow and details. The explanation is more detailed but does not introduce inaccuracies or semantic deviations, and it covers all key aspects required by the evaluation steps., error: None)

For test case:

  - input: How do EPE manual entry, Quartus-generated files, and Import Data macro collectively complete power estimation?
  - actual output: The EPE (Early Power Estimator) spreadsheet, Quartus-generated files, and the Import Data macro work together in a streamlined workflow for power estimation in FPGA designs:

1. **EPE Manual Entry**:
   - Used when no existing design exists. Designers manually input parameters like device resources, operating frequency, toggle rates, and environmental conditions into the EPE spreadsheet. This allows early-stage power estimation based on estimates.

2. **Quartus-Generated Files**:
   - If a partial or complete design exists in Intel Quartus Prime, the software generates an EPE file (`.txt` or `.csv`) containing device resource usage data. This file captures accurate resource utilization from the design, replacing manual estimates.

3. **Import Data Macro**:
   - Automates the transfer of data from the Quartus-generated EPE file into the EPE spreadsheet. Instead of manually copying/pasting resource data, the macro parses the file and populates the spreadsheet, ensuring consistency and reducing errors.

**Collective Workflow**:
- For new designs: Start with manual EPE entry.
- For existing designs: Use Quartus to generate an EPE file, then import it via the macro into the spreadsheet.
- This combination ensures accurate, efficient data integration, enabling precise power estimation early in the design cycle. Post-fit analysis can later refine results using the Intel Quartus Prime Power Analyzer.
  - expected output: EPE manual entry allows you to input estimated or known device resources and parameters directly into the Early Power Estimator spreadsheet. Quartus-generated files (.txt, .csv) provide actual device resource information from your existing or partial design, which can be imported into the EPE spreadsheet. The Import Data macro automates the transfer of this information from the Quartus-generated files into the spreadsheet. Together, these methods ensure that all relevant design data is accurately captured in the EPE spreadsheet for comprehensive power estimation.
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Answer Correctness [GEval] (score: 0.9222700143984234, threshold: 0.7, strict: False, evaluation model: gpt-4.1, reason: The actual output is factually correct and semantically aligned with the expected output, thoroughly explaining how the EPE spreadsheet is used for early power estimation, thermal planning, and PCB design. It expands on the expected output by detailing the workflow, integration with Quartus Prime, and iterative refinement, all of which are accurate and relevant. There are no factual inaccuracies or significant semantic differences, but the actual output is more detailed than required, which is a minor deviation from the expected brevity., error: None)

For test case:

  - input: How does EPE spreadsheet assist in early power budgeting and PCB design, considering thermal requirements?
  - actual output: The EPE (Early Power Estimator) spreadsheet assists in early power budgeting and PCB design by providing a framework to estimate power consumption during the initial design phases, which is critical for addressing thermal requirements. Here's how it works:

1. **Early Power Estimation**:
   - Designers can manually input parameters like device resources, operating frequency, and toggle rates into the EPE spreadsheet. This allows for preliminary power consumption estimates before the full design is finalized.
   - If using Intel Quartus Prime, the tool can generate an EPE file (.txt/.csv) from the design, which can be imported into the spreadsheet for automated data transfer. This integration ensures consistency between the design and power estimates.

2. **Thermal Planning**:
   - The EPE's power estimates inform PCB-level thermal design decisions. For example, high power estimates may require larger heat sinks, improved airflow, or additional thermal vias on the PCB.
   - By identifying power-hungry components early, designers can allocate power delivery resources (e.g., voltage regulators) and cooling solutions proactively.

3. **Iterative Refinement**:
   - The EPE serves as a baseline for power budgeting. As the design evolves, updated data from Quartus Prime can refine these estimates, ensuring thermal requirements are met as the design progresses.
   - The tool’s flexibility allows manual adjustments, accommodating changes in design scope or component selection.

4. **Guideline for Power Supplies**:
   - Early power estimates guide the selection of power supplies and voltage regulators, ensuring they can handle the estimated load while meeting thermal constraints.

In summary, the EPE spreadsheet enables designers to address power and thermal challenges early in the PCB design process, reducing risks of late-stage redesigns or thermal failures. For precise validation, the Intel Quartus Prime Power Analyzer is used later in the workflow.
  - expected output: The Early Power Estimator (EPE) spreadsheet helps estimate power consumption early in the design cycle, allowing you to plan power budgets and design the PCB accordingly. By providing early estimates, it ensures you can address both power supply and thermal requirements—such as ensuring the cooling solution is sufficient and the computed junction temperature stays within device specifications—before finalizing your design.
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Answer Correctness [GEval] (score: 0.9222700149143159, threshold: 0.7, strict: False, evaluation model: gpt-4.1, reason: The actual output is factually correct and semantically aligned with the expected output, providing a detailed comparison of the EPE spreadsheet and Power Analyzer, including their roles, timing, accuracy, and use cases. It expands on the expected output by adding specifics about data sources, accuracy levels, and workflow integration, but does not introduce any factual inaccuracies or significant semantic differences. The only minor shortcoming is that it is more detailed than required, but this does not detract from correctness or meaning., error: None)

For test case:

  - input: How do EPE spreadsheet and Power Analyzer in Quartus Prime assist in pre- and post-design power estimation?
  - actual output: The **EPE (Early Power Estimator) spreadsheet** and **Intel Quartus Prime Power Analyzer** serve complementary roles in power estimation across different design stages:

### **Pre-Design (Early Estimation) - EPE Spreadsheet**
1. **Manual Input or Auto-Generated Data**:
   - Designers can manually enter device resources (e.g., LUTs, FFs), clock frequencies, toggle rates, and environmental conditions.
   - Alternatively, Quartus Prime can generate an EPE file (`.txt`/`.csv`) with resource estimates from a partial or incomplete design.
2. **Purpose**:
   - Provides a **rough estimate** of power consumption early in the design cycle.
   - Helps identify power-critical areas before detailed implementation.
3. **Accuracy**:
   - Moderate accuracy due to reliance on estimates (e.g., assumed toggle rates or resource usage).

---

### **Post-Design (Accurate Estimation) - Power Analyzer**
1. **Post-Fit Analysis**:
   - Uses actual placement and routing results from Quartus Prime to calculate power.
   - Incorporates post-synthesis data (e.g., signal activity, register transfer level (RTL) simulations).
2. **Detailed Metrics**:
   - Outputs precise values for thermal power, dynamic power, static power, and off-chip power.
   - Includes breakdowns by clock domain, block type, or hierarchy.
3. **Accuracy**:
   - **High accuracy** (medium to very high) because it reflects the final design’s physical implementation.

---

### **Key Differences**
| **Aspect**               | **EPE Spreadsheet**               | **Power Analyzer**                  |
|--------------------------|-----------------------------------|-------------------------------------|
| **Timing**               | Pre-design or early design        | Post-design (after synthesis/fitting) |
| **Data Sources**         | Estimated resource usage          | Actual placement/routing data       |
| **Accuracy**             | Medium                            | Medium to very high                 |
| **Use Case**             | Initial power budgeting           | Final power validation              |

By using both tools sequentially, designers can iteratively refine power estimates, ensuring compliance with thermal and power constraints throughout the design flow.
  - expected output: The Early Power Estimator (EPE) spreadsheet in Quartus Prime helps you estimate power consumption early in the design cycle, before compilation or source code creation, allowing you to plan power budgets and design appropriate power supplies and cooling solutions. After your design is complete, the Power Analyzer provides a more accurate analysis of actual power consumption, ensuring your design meets thermal and power supply requirements.
  - context: None
  - retrieval context: None

======================================================================

Metrics Summary

  - ✅ Answer Correctness [GEval] (score: 0.7991014767576546, threshold: 0.7, strict: False, evaluation model: gpt-4.1, reason: The actual output accurately describes Pin Planner's role in early FPGA I/O planning and validation, aligning with the expected output's focus on early pin assignment and error prevention. It covers early assignment, validation, iterative refinement, and integration with PCB tools, which matches the expected output's emphasis on early specification, validation, and error avoidance. However, it omits explicit mention of interfacing with the IP core parameter editor and the automatic validation during compilation, which are present in the expected output. Overall, the factual and semantic alignment is strong, with only minor omissions., error: None)

For test case:

  - input: How does Pin Planner enable early FPGA I/O interface planning and validation using I/O Assignment Analysis?
  - actual output: Pin Planner enables early FPGA I/O interface planning and validation through I/O Assignment Analysis by allowing designers to assign and verify pin configurations *before* finalizing the HDL design. Here's how it works:

1. **Early Pin Assignment**:
   - Users can assign I/O pins (e.g., selecting banks, voltage groups, differential pairs) directly in the Pin Planner, even while developing the top-level HDL wrapper or during early design stages. This avoids late-stage constraints.

2. **I/O Assignment Analysis**:
   - The tool runs validation checks to ensure assignments meet device/PCB requirements (e.g., voltage standards, loading, slew rate).
   - It generates a synthesized netlist, which can be used to identify and fix issues (e.g., timing violations, conflicts) early in the process.

3. **Iterative Refinement**:
   - Designers can repeat the analysis after modifying assignments, ensuring continuous validation. This reduces the risk of errors in later stages.

4. **Integration with PCB Tools**:
   - Pin assignments can be exported to PCB design tools (via .qsf/.pin files) for validation, ensuring consistency between FPGA and board layouts.

By enabling early planning and validation, Pin Planner helps optimize I/O performance, reduce design revisions, and improve time-to-market.
  - expected output: Pin Planner enables early FPGA I/O interface planning by allowing designers to specify and assign top-level I/O pins before source code development, based on system requirements and standard interfaces. It interfaces with the IP core parameter editor for custom or imported IP cores, letting you configure connections and create I/O-related assignments. I/O Assignment Analysis then validates these assignments against the target FPGA architecture, ensuring pin locations and assignments are supported. This validation runs automatically during compilation, helping to catch errors early and avoid board design changes.
  - context: None
  - retrieval context: None

======================================================================

Overall Metric Pass Rates

Answer Correctness [GEval]: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=678484;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 5.92s | token cost: 0.012556000000000001 USD)
» Test Results (4 total tests):
   » Pass Rate: 100.0% | Passed: 4 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

In [33]:
import pandas as pd

flattened_results = []


for result in eval_res.test_results:
    row = {
        "Test Case": result.name,
        "Input": result.input,
        "Actual Output": result.actual_output,
        "Expected Output": result.expected_output,
        "Success": result.success
    }

    for metric in result.metrics_data:
        row[f"{metric.name} Score"] = metric.score
        row[f"{metric.name} Reason"] = metric.reason

    flattened_results.append(row)

df_results = pd.DataFrame(flattened_results)
df_results

,Test Case,Input,Actual Output,Expected Output,Success,Answer Correctness [GEval] Score,Answer Correctness [GEval] Reason
0,test_case_2,"How do EPE manual entry, Quartus-generated fil...","The EPE (Early Power Estimator) spreadsheet, Q...",EPE manual entry allows you to input estimated...,True,0.985195,The actual output is factually correct and sem...
1,test_case_1,How does EPE spreadsheet assist in early power...,The EPE (Early Power Estimator) spreadsheet as...,The Early Power Estimator (EPE) spreadsheet he...,True,0.922270,The actual output is factually correct and sem...
2,test_case_0,How do EPE spreadsheet and Power Analyzer in Q...,The **EPE (Early Power Estimator) spreadsheet*...,The Early Power Estimator (EPE) spreadsheet in...,True,0.922270,The actual output is factually correct and sem...
3,test_case_3,How does Pin Planner enable early FPGA I/O int...,Pin Planner enables early FPGA I/O interface p...,Pin Planner enables early FPGA I/O interface p...,True,0.799101,The actual output accurately describes Pin Pla...